export const SET_MOVIES = 'SET_MOVIES';
export const SET_MOVIES_FILTER = 'SET_MOVIES_FILTER';
export const SET_MOVIES_FILTER_GENDER = 'SET_MOVIES_FILTER_GENDER';
export const SET_MOVIES_FILTER_YEAR = 'SET_MOVIES_FILTER_YEAR';
