export const SET_MOVIES = 'SET_MOVIES';
export const SET_TOP_RATED_MOVIES = 'SET_TOP_RATED_MOVIES';
export const SET_MOVIES_FILTER_SORT_BY = 'SET_MOVIES_FILTER_SORT_BY';
export const SET_MOVIES_FILTER_GENDER = 'SET_MOVIES_FILTER_GENDER';
export const SET_MOVIES_FILTER_YEAR = 'SET_MOVIES_FILTER_YEAR';
